# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

touint8 <- function(arr, dim) {
    .Call(`_RFPNG_touint8`, arr, dim)
}

fromuint8 <- function(arr, x, y, z) {
    .Call(`_RFPNG_fromuint8`, arr, x, y, z)
}

#' Encode to file
#' @param x integer matrix
#' @param file_path character. file to write to
#' @return bool
writeFPNG <- function(x, file_path) {
    .Call(`_RFPNG_writeFPNG`, x, file_path)
}

decode_from_file <- function(file_path) {
    .Call(`_RFPNG_decode_from_file`, file_path)
}

