# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

init_fpng <- function() {
    invisible(.Call(`_RFPNG_init_fpng`))
}

touint8 <- function(arr, dim) {
    .Call(`_RFPNG_touint8`, arr, dim)
}

fromuint8 <- function(arr, x, y, z) {
    .Call(`_RFPNG_fromuint8`, arr, x, y, z)
}

#' Encode to file
#' Create a FPNG image from an array or matrix.
#' @param x image represented by an integer matrix with values between 0 and
#' 255. Either three (RGB) or four (RGB+alpha) planes.
#' @param file_path character. file to write to
#' @return bool
#' @export
writeFPNG <- function(x, file_path) {
    invisible(.Call(`_RFPNG_writeFPNG`, x, file_path))
}

#' Decode from file
#' Reads an image from a PNG file into a raster array.
#' @param file_path character. file to write to
#' @return array representing the FPNG image
#' @export
readFPNG <- function(file_path) {
    .Call(`_RFPNG_readFPNG`, file_path)
}

